name: Publish Action
on:
  release:
    types: [published]

jobs:
  publish_release:
    if: github.repository_owner == 'synodic'
    uses: synodic/.github/.github/workflows/action-publish.yml@stable
