name: Python Merge

on:
  workflow_call:
    inputs:
      repository_url:
        required: true
        type: string
    secrets:
      PYPI_API_TOKEN:
        required: true
jobs:
  pypi_development_deployment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0    # Fetch entire history for tags
          filter: blob:none # Exclude file contents for speed

      - name: Semantic Version
        id: version
        uses: PaulHatch/semantic-version@v6.0.1
        with:
          tag_prefix: "v"
          version_format: "${major}.${minor}.${patch}"

      - name: Draft
        id: draft-release
        uses: release-drafter/release-drafter@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install PDM
        uses: pdm-project/setup-pdm@v4
        with:
          python-version: "3.14"
          cache: true

      - name: Set Tag
        id: set-tag
        run: |
          version=${{steps.version.outputs.version}}.dev${{github.run_number}}
          echo "version=${version}" >> $GITHUB_OUTPUT

      - name: Tag Development Version
        env:
          TAG: ${{steps.set-tag.outputs.version}}
        run: git tag $TAG

      - name: Build
        run: pdm build -d dist

      - name: Publish
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
          repository-url: ${{ inputs.repository_url }}
